# -*- coding: utf-8 -*-
"""Dados PIBIC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yY19a16zAyS2rpA8XgBTUCuOYqznLGsc

Dados: amostra público feminino
"""

!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

!pip install selenium
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--no-sandbox')
driver = webdriver.Chrome('chromedriver', options = options)

!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

!pip install selenium
from selenium import webdriver

from bs4 import BeautifulSoup as bs

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--no-sandbox')
driver = webdriver.Chrome('chromedriver', options = options)

driver.get('https://www.google.com/search?q=intitle%3Astore+intext%3Awomen%27s+clothing+site%3Ainstagram.com&oq=intitle%3Astore+intext%3Awomen%27s+clothing+site%3Ainstagram.com&aqs=chrome..69i57j69i58.4235j0j9&sourceid=chrome&ie=UTF-8')
try:
    for i in range(300):
        source = driver.page_source
        soup = bs(source)
        titles = []
        for tag in soup.findAll(class_ = 'LC20lb DKV0Md'): 
            texto = tag.get_text()
            titles.append(texto)
        titles = list(set(titles))
        print(titles)
        proximo = driver.find_element_by_id('pnnext')
        proximo.click()
       
except:
  print(titles)

"""Dados: amostra público masculino"""

!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

!pip install selenium
from selenium import webdriver

from bs4 import BeautifulSoup as bs

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--no-sandbox')
driver = webdriver.Chrome('chromedriver', options = options)

driver.get('https://www.google.com/search?q=intitle%3Astore+intext%3Amen%27s+clothing+site%3Ainstagram.com&oq=intitle%3Astore+intext%3Amen%27s+clothing+site%3Ainstagram.com&aqs=chrome..69i57j69i58.510j0j9&sourceid=chrome&ie=UTF-8')
try:
    for i in range(300):
        source = driver.page_source
        soup = bs(source)
        titles2 = []
        for tag in soup.findAll(class_ = 'LC20lb DKV0Md'): 
            texto = tag.get_text()
            titles2.append(texto)
        titles2 = list(set(titles2))
        print(titles2)
        proximo = driver.find_element_by_id('pnnext')
        proximo.click()
       
except:
  print(titles2)